# Generated by Django 5.1.1 on 2024-09-25 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furniture', '0002_remove_furniture_photo_furniture_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='furniture',
            name='price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
